# Generated by Django 3.2.11 on 2022-01-08 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_register'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
