# Generated by Django 3.2.11 on 2022-01-12 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0006_booking'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='places',
            table='Places',
        ),
    ]
